/* eslint-disable react-refresh/only-export-components */
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Canvas, useFrame, useThree, type ThreeEvent } from '@react-three/fiber';
import { ContactShadows, OrbitControls, RoundedBox } from '@react-three/drei';
import * as THREE from 'three';

/* ═════════════════════════════ 1. PRIMITIVES ═════════════════════════════ */

/**
 * Strict CSS hex color — `#rgb` or `#rrggbb`.
 *
 * String literals are validated at compile time:
 *   `const ok:  HexColor = '#ff0044'`  ✅
 *   `const bad: HexColor = 'red'`      ❌ compile error
 *
 * For dynamic strings (API, color picker) use the `hex()` helper below.
 * Prefer lenient typing? Change to: `type HexColor = ` + "`#${string}`" + `.
 */
export type HexColor = `#${string}`;

const HEX_RE = /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;

/** Type guard: is this value a valid hex color string? */
export const isHexColor = (value: unknown): value is HexColor =>
    typeof value === 'string' && HEX_RE.test(value);

/** Runtime-validate + cast a dynamic string (API, color picker, …) to `HexColor`. */
export function hex(value: string): HexColor {
    if (!HEX_RE.test(value)) throw new Error(`[Office3D] Invalid hex color: "${value}"`);
    return value as HexColor;
}

/** 3D point `[x, y, z]` in meters. */
export type Vec3 = [x: number, y: number, z: number];
/** 2D ground-plane point `[x, z]` in meters. */
export type Vec2 = [x: number, z: number];

/**
 * Identifier of an assignable seat, generated by `resolveStations()`:
 *   desks → `desk-0`, `desk-1`, … · table → `table-0`, `table-1`, …
 * Typos such as `'desks-0'` or `'desk'` are caught at compile time.
 */
export type StationId = `desk-${number}` | `table-${number}`;

/** Furniture category. */
export type StationKind = 'desk' | 'table';

/** Exhaustiveness helper for discriminated unions. */
export function assertNever(value: never, context = ''): never {
    throw new Error(`[Office3D] Unhandled variant${context ? ` (${context})` : ''}: ${JSON.stringify(value)}`);
}

/* ═════════════════════════════ 2. LAYOUT TYPES ════════════════════════════ */

/**
 * Office layout configuration. All fields optional — omitted fields fall back
 * to their documented default (or `'auto'` where noted).
 */
export interface OfficeLayout {
    /** Number of desk stations, arranged as a centered grid. @default 4 @min 0 */
    desks?: number;
    /**
     * Desks per grid row.
     * - `number` — exact count (clamped to `[1, desks]`)
     * - `'auto'` — `ceil(√desks)`, i.e. a roughly square grid
     * @default 'auto'
     */
    desksPerRow?: number | 'auto';
    /** Horizontal distance between desks, meters. @default 2.7 @min 1 */
    deskGap?: number;
    /** Depth distance between desk rows, meters. @default 3.1 @min 1 */
    rowGap?: number;
    /** Rotate every odd row 180° (back-to-back rows, like an open-plan office). @default false */
    faceAlternate?: boolean;
    /** Render the round meeting table. @default true */
    table?: boolean;
    /** Number of stools (assignable seats) around the table. @default 4 @min 1 @max 12 */
    tableSeats?: number;
    /**
     * Table center `[x, z]` in meters, or `'auto'` to place it behind the desk grid.
     * @default 'auto'
     */
    tablePosition?: Vec2 | 'auto';
}

/** `OfficeLayout` with every field filled in — what the layout engine consumes. */
export interface ResolvedOfficeLayout {
    desks: number;
    desksPerRow: number;
    deskGap: number;
    rowGap: number;
    faceAlternate: boolean;
    table: boolean;
    tableSeats: number;
    tablePosition: Vec2;
}

/* ═════════════════════════════ 3. AVATAR TYPES ════════════════════════════ */

/**
 * Avatar appearance & behavior. All fields optional.
 * Colors must be strict hex — literals are compile-checked, dynamic strings
 * go through `hex()`.
 */
export interface AvatarConfig {
    /** Skin tone. @default '#ffcf9f' */
    skinColor?: HexColor;
    /** Hair color. @default '#2f2118' */
    hairColor?: HexColor;
    /** Shirt color. @default '#5b7cfa' */
    shirtColor?: HexColor;
    /** Pants color. @default '#2d3748' */
    pantsColor?: HexColor;
    /** Shoe color. @default '#1a202c' */
    shoeColor?: HexColor;
    /** Iris color. @default '#22223b' */
    eyeColor?: HexColor;
    /** Head turns to follow the pointer. @default true */
    followMouse?: boolean;
    /** Hands type on the keyboard (desks only; ignored at the table). @default true */
    typing?: boolean;
}

/** `AvatarConfig` with every field filled in — what the renderer consumes. */
export type ResolvedAvatarConfig = Required<AvatarConfig>;

/** `StationId → AvatarConfig` — pass as the `avatars` prop. */
export type AvatarAssignments = Partial<Record<StationId, AvatarConfig>>;

/** Canonical defaults, frozen. */
export const DEFAULT_AVATAR: Readonly<ResolvedAvatarConfig> = Object.freeze({
    skinColor: '#ffcf9f',
    hairColor: '#2f2118',
    shirtColor: '#5b7cfa',
    pantsColor: '#2d3748',
    shoeColor: '#1a202c',
    eyeColor: '#22223b',
    followMouse: true,
    typing: true,
} as const satisfies ResolvedAvatarConfig);

/** Fill in omitted avatar fields with defaults. */
export function resolveAvatar(config: AvatarConfig = {}): ResolvedAvatarConfig {
    return { ...DEFAULT_AVATAR, ...config };
}

/* ══════════════════════════ 4. RUNTIME VALIDATORS ═════════════════════════ */

/** Type guard for `AvatarConfig` (e.g. before trusting API data). */
export const isAvatarConfig = (value: unknown): value is AvatarConfig => {
    if (typeof value !== 'object' || value === null) return false;
    const v = value as Record<string, unknown>;
    const colors = ['skinColor', 'hairColor', 'shirtColor', 'pantsColor', 'shoeColor', 'eyeColor'] as const satisfies readonly (keyof AvatarConfig)[];
    const bools = ['followMouse', 'typing'] as const satisfies readonly (keyof AvatarConfig)[];
    return (
        colors.every((k) => v[k] === undefined || isHexColor(v[k])) &&
        bools.every((k) => v[k] === undefined || typeof v[k] === 'boolean')
    );
};

/** Type guard for `AvatarAssignments` (all values must be valid configs). */
export const isAvatarAssignments = (value: unknown): value is AvatarAssignments =>
    typeof value === 'object' && value !== null && Object.values(value).every(isAvatarConfig);

/** Type guard for `OfficeLayout`. */
export const isOfficeLayout = (value: unknown): value is OfficeLayout => {
    if (typeof value !== 'object' || value === null) return false;
    const v = value as Record<string, unknown>;
    const num = (x: unknown): x is number => typeof x === 'number' && Number.isFinite(x);
    return (
        (v.desks === undefined || (num(v.desks) && v.desks >= 0)) &&
        (v.desksPerRow === undefined || v.desksPerRow === 'auto' || (num(v.desksPerRow) && v.desksPerRow >= 1)) &&
        (v.deskGap === undefined || (num(v.deskGap) && v.deskGap >= 1)) &&
        (v.rowGap === undefined || (num(v.rowGap) && v.rowGap >= 1)) &&
        (v.faceAlternate === undefined || typeof v.faceAlternate === 'boolean') &&
        (v.table === undefined || typeof v.table === 'boolean') &&
        (v.tableSeats === undefined || (num(v.tableSeats) && v.tableSeats >= 1)) &&
        (v.tablePosition === undefined || v.tablePosition === 'auto' ||
            (Array.isArray(v.tablePosition) && v.tablePosition.length === 2 && v.tablePosition.every(num)))
    );
};

/* ═════════════════════════════ 5. STATION DEFS ════════════════════════════ */

export interface DeskStation {
    readonly kind: 'desk';
    readonly id: `desk-${number}`;
    readonly position: Vec3;
    readonly rotationY: number;
    readonly seat: { readonly position: Vec3; readonly rotationY: number };
    readonly hoverRadius: number;
}

export interface TableSeat {
    readonly id: `table-${number}`;
    readonly position: Vec3;
    readonly rotationY: number;
}

export interface TableStation {
    readonly kind: 'table';
    readonly id: 'table';
    readonly position: Vec3;
    readonly hoverRadius: number;
    readonly seats: readonly TableSeat[];
}

export type StationDef = DeskStation | TableStation;

const clampNum = (v: number, min: number, max: number): number =>
    Math.min(max, Math.max(min, v));

/* ═══════════════════════════ 6. LAYOUT ENGINE ═════════════════════════════ */

/** Resolve defaults + clamp values. Pure — safe to call in render. */
export function resolveLayout(layout: OfficeLayout = {}): ResolvedOfficeLayout {
    const desks = clampNum(Math.floor(layout.desks ?? 4), 0, 500);
    const desksPerRow =
        layout.desksPerRow === 'auto' || layout.desksPerRow === undefined
            ? Math.max(1, Math.ceil(Math.sqrt(desks)))
            : clampNum(Math.floor(layout.desksPerRow), 1, Math.max(1, desks));
    const deskGap = clampNum(layout.deskGap ?? 2.7, 1, 20);
    const rowGap = clampNum(layout.rowGap ?? 3.1, 1, 20);
    const faceAlternate = layout.faceAlternate ?? false;
    const table = layout.table ?? true;
    const tableSeats = clampNum(Math.floor(layout.tableSeats ?? 4), 1, 12);

    // 'auto': behind the desk grid (row 0 sits closest to the camera, +z)
    const rows = desks > 0 ? Math.ceil(desks / desksPerRow) : 0;
    const minZ = desks > 0 ? -((rows - 1) / 2) * rowGap - 0.5 : 0;
    const tablePosition: Vec2 =
        layout.tablePosition === 'auto' || layout.tablePosition === undefined
            ? [0, minZ - 2.6]
            : [layout.tablePosition[0], layout.tablePosition[1]];

    return { desks, desksPerRow, deskGap, rowGap, faceAlternate, table, tableSeats, tablePosition };
}

/** Defaults for reference / UIs. */
export const DEFAULT_LAYOUT: Readonly<ResolvedOfficeLayout> = resolveLayout();

/**
 * Pure layout → stations resolver. Call it yourself to enumerate ids for your UI.
 * Ids are stable and order-independent: `desk-{index}`, `table-{seatIndex}`.
 */
export function resolveStations(layout: OfficeLayout = {}): StationDef[] {
    const L = resolveLayout(layout);
    const stations: StationDef[] = [];

    for (let i = 0; i < L.desks; i++) {
        const row = Math.floor(i / L.desksPerRow);
        const col = i % L.desksPerRow;
        const inRow = Math.min(L.desksPerRow, L.desks - row * L.desksPerRow);
        const x = (col - (inRow - 1) / 2) * L.deskGap;
        const z = ((rows(L) - 1) / 2 - row) * L.rowGap;
        stations.push({
            kind: 'desk',
            id: `desk-${i}`,
            position: [x, 0, z],
            rotationY: L.faceAlternate && row % 2 === 1 ? Math.PI : 0,
            seat: { position: [0, 0, -0.45], rotationY: 0 },
            hoverRadius: 1.5,
        });
    }

    if (L.table) {
        const [tx, tz] = L.tablePosition;
        stations.push({
            kind: 'table',
            id: 'table',
            position: [tx, 0, tz],
            hoverRadius: 1.6,
            seats: Array.from({ length: L.tableSeats }, (_, k) => {
                const a = (k / L.tableSeats) * Math.PI * 2 + Math.PI / 2;
                return {
                    id: `table-${k}`,
                    position: [Math.sin(a) * 1.2, 0, Math.cos(a) * 1.2],
                    rotationY: a + Math.PI,
                };
            }),
        });
    }
    return stations;

    function rows(l: ResolvedOfficeLayout): number {
        return l.desks > 0 ? Math.ceil(l.desks / l.desksPerRow) : 0;
    }
}

/** All assignable station ids for a set of stations. */
export function stationIds(stations: readonly StationDef[]): StationId[] {
    return stations.flatMap((s) => (s.kind === 'desk' ? [s.id] : s.seats.map((t) => t.id)));
}

const DESK_TOP = 0.785;
const HAND_Y = -0.27;

/* ═══════════════════════════ 7. 3D COMPONENTS ═════════════════════════════ */

const Appear: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const ref = useRef<THREE.Group>(null!);
    useFrame((_, delta) => {
        const s = THREE.MathUtils.damp(ref.current.scale.x, 1, 6, delta);
        ref.current.scale.setScalar(Math.max(s, 0.0001));
    });
    return <group ref={ref} scale={0.0001}>{children}</group>;
};

function useScreenTexture(): THREE.CanvasTexture {
    const tex = useMemo(() => {
        const c = document.createElement('canvas');
        c.width = 256; c.height = 160;
        const ctx = c.getContext('2d')!;
        ctx.fillStyle = '#0d1526'; ctx.fillRect(0, 0, 256, 160);
        ctx.fillStyle = '#1c2941'; ctx.fillRect(0, 0, 256, 16);
        ['#ff6b6b', '#f7c948', '#51cf66'].forEach((col, i) => {
            ctx.fillStyle = col;
            ctx.beginPath(); ctx.arc(12 + i * 14, 8, 3.2, 0, Math.PI * 2); ctx.fill();
        });
        const palette = ['#7dd3fc', '#c4b5fd', '#86efac', '#fca5a5', '#fde68a'];
        for (let row = 0, y = 26; y < 152; row++, y += 11) {
            ctx.fillStyle = palette[row % palette.length];
            ctx.fillRect(10 + (row % 4) * 10, y, 28 + ((row * 53) % 130), 5);
        }
        const t = new THREE.CanvasTexture(c);
        t.colorSpace = THREE.SRGBColorSpace;
        return t;
    }, []);
    useEffect(() => () => { tex.dispose(); }, [tex]);
    return tex;
}

const Laptop: React.FC<{ position?: Vec3; rotationY?: number; on?: boolean }> = ({
    position = [0, 0, 0], rotationY = 0, on = true,
}) => {
    const tex = useScreenTexture();
    return (
        <group position={position} rotation={[0, rotationY, 0]}>
            <RoundedBox args={[0.62, 0.035, 0.44]} radius={0.012} smoothness={3} position={[0, 0.018, 0]}>
                <meshStandardMaterial color="#2b3140" roughness={0.5} metalness={0.35} />
            </RoundedBox>
            <mesh position={[0, 0.037, 0.07]}>
                <boxGeometry args={[0.5, 0.006, 0.17]} />
                <meshStandardMaterial color="#161b26" roughness={0.9} />
            </mesh>
            <mesh position={[0, 0.036, -0.12]}>
                <boxGeometry args={[0.18, 0.004, 0.11]} />
                <meshStandardMaterial color="#3a4152" roughness={0.4} metalness={0.3} />
            </mesh>
            <group position={[0, 0.03, 0.2]} rotation={[0.25, 0, 0]}>
                <RoundedBox args={[0.62, 0.44, 0.024]} radius={0.01} smoothness={3} position={[0, 0.22, 0]}>
                    <meshStandardMaterial color="#2b3140" roughness={0.5} metalness={0.35} />
                </RoundedBox>
                <mesh position={[0, 0.22, -0.014]} rotation={[0, Math.PI, 0]}>
                    <planeGeometry args={[0.56, 0.37]} />
                    {on
                        ? <meshBasicMaterial map={tex} toneMapped={false} />
                        : <meshStandardMaterial color="#0a0f1a" roughness={0.25} metalness={0.2} />}
                </mesh>
                {on && <pointLight position={[0, 0.24, -0.25]} intensity={0.9} distance={1.1} decay={1.8} color="#9ec1ff" />}
                <mesh position={[0, 0.3, 0.014]}>
                    <circleGeometry args={[0.028, 24]} />
                    <meshBasicMaterial color={on ? '#7dd3fc' : '#3a4152'} />
                </mesh>
            </group>
        </group>
    );
};

const DeskLamp: React.FC<{
    position?: Vec3;
    rotationY?: number;
    on: boolean;
    onToggle: (next: boolean) => void;
}> = ({ position = [0, 0, 0], rotationY = 0, on, onToggle }) => (
    <group
        position={position}
        rotation={[0, rotationY, 0]}
        onClick={(e: ThreeEvent<MouseEvent>) => { e.stopPropagation(); onToggle(!on); }}
        onPointerOver={(e: ThreeEvent<PointerEvent>) => { e.stopPropagation(); document.body.style.cursor = 'pointer'; }}
        onPointerOut={() => { document.body.style.cursor = 'auto'; }}
    >
        <mesh position={[0, 0.015, 0]}>
            <cylinderGeometry args={[0.13, 0.15, 0.03, 24]} />
            <meshStandardMaterial color="#334155" roughness={0.4} metalness={0.6} />
        </mesh>
        <mesh position={[0.09, 0.2, 0]} rotation={[0, 0, -0.47]}>
            <cylinderGeometry args={[0.02, 0.02, 0.4, 12]} />
            <meshStandardMaterial color="#334155" roughness={0.35} metalness={0.7} />
        </mesh>
        <mesh position={[0.08, 0.5, 0]} rotation={[0, 0, 0.7]}>
            <cylinderGeometry args={[0.02, 0.02, 0.31, 12]} />
            <meshStandardMaterial color="#334155" roughness={0.35} metalness={0.7} />
        </mesh>
        <group position={[-0.03, 0.63, 0]} rotation={[0, 0, 0.45]}>
            <mesh>
                <cylinderGeometry args={[0.055, 0.12, 0.14, 24, 1, true]} />
                <meshStandardMaterial color="#f59e0b" roughness={0.5} metalness={0.3} side={THREE.DoubleSide} />
            </mesh>
            <mesh position={[0, -0.04, 0]}>
                <sphereGeometry args={[0.035, 12, 12]} />
                <meshStandardMaterial color="#fff7e0" emissive="#ffd27a" emissiveIntensity={on ? 2.5 : 0} />
            </mesh>
        </group>
        <pointLight position={[-0.02, 0.5, 0.05]} color="#ffd9a3" intensity={on ? 8 : 0} distance={3.2} decay={1.6} />
    </group>
);

const Desk: React.FC = () => (
    <group>
        <RoundedBox args={[1.8, 0.07, 0.85]} radius={0.02} smoothness={3} position={[0, 0.75, 0]}>
            <meshStandardMaterial color="#a9744f" roughness={0.6} />
        </RoundedBox>
        {[-1, 1].map((s) => (
            <mesh key={s} position={[s * 0.84, 0.36, 0]}>
                <boxGeometry args={[0.06, 0.72, 0.78]} />
                <meshStandardMaterial color="#3d4557" roughness={0.5} metalness={0.3} />
            </mesh>
        ))}
        <mesh position={[0, 0.52, -0.38]}>
            <boxGeometry args={[1.55, 0.3, 0.035]} />
            <meshStandardMaterial color="#374052" roughness={0.6} />
        </mesh>
    </group>
);

const OfficeChair: React.FC<{ position?: Vec3; accent?: string }> = ({
    position = [0, 0, 0], accent = '#3d4557',
}) => (
    <group position={position}>
        <mesh position={[0, 0.03, 0]}>
            <cylinderGeometry args={[0.28, 0.3, 0.05, 24]} />
            <meshStandardMaterial color="#20242e" roughness={0.7} />
        </mesh>
        <mesh position={[0, 0.24, 0]}>
            <cylinderGeometry args={[0.045, 0.05, 0.36, 12]} />
            <meshStandardMaterial color="#565f73" roughness={0.35} metalness={0.7} />
        </mesh>
        <RoundedBox args={[0.52, 0.09, 0.5]} radius={0.03} smoothness={3} position={[0, 0.46, 0]}>
            <meshStandardMaterial color={accent} roughness={0.8} />
        </RoundedBox>
        <RoundedBox args={[0.5, 0.56, 0.08]} radius={0.03} smoothness={3} position={[0, 0.86, -0.23]}>
            <meshStandardMaterial color={accent} roughness={0.8} />
        </RoundedBox>
    </group>
);

const Stool: React.FC = () => (
    <group>
        <mesh position={[0, 0.5, 0]}>
            <cylinderGeometry args={[0.24, 0.22, 0.07, 20]} />
            <meshStandardMaterial color="#8d6e63" roughness={0.7} />
        </mesh>
        <mesh position={[0, 0.25, 0]}>
            <cylinderGeometry args={[0.035, 0.035, 0.44, 12]} />
            <meshStandardMaterial color="#3d4557" roughness={0.4} metalness={0.6} />
        </mesh>
        <mesh position={[0, 0.03, 0]}>
            <cylinderGeometry args={[0.2, 0.22, 0.05, 20]} />
            <meshStandardMaterial color="#3d4557" roughness={0.4} metalness={0.6} />
        </mesh>
    </group>
);

const RoundTable: React.FC = () => (
    <group>
        <mesh position={[0, 0.72, 0]}>
            <cylinderGeometry args={[0.85, 0.85, 0.06, 40]} />
            <meshStandardMaterial color="#a9744f" roughness={0.6} />
        </mesh>
        <mesh position={[0, 0.36, 0]}>
            <cylinderGeometry args={[0.08, 0.1, 0.66, 16]} />
            <meshStandardMaterial color="#3d4557" roughness={0.4} metalness={0.5} />
        </mesh>
        <mesh position={[0, 0.04, 0]}>
            <cylinderGeometry args={[0.34, 0.38, 0.06, 28]} />
            <meshStandardMaterial color="#3d4557" roughness={0.4} metalness={0.5} />
        </mesh>
        <group position={[0.3, 0.75, 0.18]}>
            <mesh position={[0, 0.05, 0]}>
                <cylinderGeometry args={[0.05, 0.045, 0.1, 16]} />
                <meshStandardMaterial color="#f7f3ec" roughness={0.6} />
            </mesh>
            <mesh position={[0.062, 0.05, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <torusGeometry args={[0.03, 0.008, 8, 16]} />
                <meshStandardMaterial color="#f7f3ec" roughness={0.6} />
            </mesh>
        </group>
        <mesh position={[-0.22, 0.758, -0.12]} rotation={[0, 0.4, 0]}>
            <boxGeometry args={[0.3, 0.006, 0.4]} />
            <meshStandardMaterial color="#f4f6fb" roughness={0.9} />
        </mesh>
    </group>
);

const DeskPlant: React.FC<{ position?: Vec3 }> = ({ position = [0, 0, 0] }) => (
    <group position={position}>
        <mesh position={[0, 0.055, 0]}>
            <cylinderGeometry args={[0.06, 0.05, 0.11, 16]} />
            <meshStandardMaterial color="#d97757" roughness={0.8} />
        </mesh>
        {([[0, 0.16, 0, 0.07], [0.04, 0.2, 0.02, 0.055], [-0.04, 0.19, -0.02, 0.05]] as const).map(([x, y, z, r], i) => (
            <mesh key={i} position={[x, y, z]}>
                <sphereGeometry args={[r, 12, 12]} />
                <meshStandardMaterial color={i === 0 ? '#2f9e63' : '#3fb377'} roughness={0.9} />
            </mesh>
        ))}
    </group>
);

const BookStack: React.FC<{ position?: Vec3 }> = ({ position = [0, 0, 0] }) => (
    <group position={position}>
        <mesh position={[0, 0.02, 0]} rotation={[0, 0.15, 0]}>
            <boxGeometry args={[0.34, 0.04, 0.24]} />
            <meshStandardMaterial color="#e15b64" roughness={0.8} />
        </mesh>
        <mesh position={[0.01, 0.055, 0]} rotation={[0, -0.1, 0]}>
            <boxGeometry args={[0.3, 0.035, 0.22]} />
            <meshStandardMaterial color="#4d96d9" roughness={0.8} />
        </mesh>
    </group>
);

/* --------------------------- Seated avatar -------------------------------- */

const SeatedHead: React.FC<{ skin: HexColor; hair: HexColor; eye: HexColor; follow: boolean }> = ({
    skin, hair, eye, follow,
}) => {
    const group = useRef<THREE.Group>(null!);
    const eyes = useRef<THREE.Group>(null!);

    useFrame((state, delta) => {
        const t = state.clock.elapsedTime;
        if (group.current) {
            const ry = follow ? state.pointer.x * 0.5 : 0;
            const rx = -0.1 + (follow ? -state.pointer.y * 0.22 : 0) + Math.sin(t * 0.9) * 0.02;
            group.current.rotation.y = THREE.MathUtils.damp(group.current.rotation.y, ry, 5, delta);
            group.current.rotation.x = THREE.MathUtils.damp(group.current.rotation.x, rx, 5, delta);
        }
        if (eyes.current) {
            const closed = t % 4 > 3.85;
            eyes.current.scale.y = THREE.MathUtils.damp(eyes.current.scale.y, closed ? 0.08 : 1, 30, delta);
        }
    });

    return (
        <group ref={group} position={[0, 1.44, 0.1]}>
            <mesh>
                <sphereGeometry args={[0.46, 32, 32]} />
                <meshStandardMaterial color={skin} roughness={0.65} />
            </mesh>
            <mesh position={[0, 0.05, -0.02]} rotation={[-0.15, 0, 0]}>
                <sphereGeometry args={[0.49, 32, 24, 0, Math.PI * 2, 0, Math.PI * 0.42]} />
                <meshStandardMaterial color={hair} roughness={0.9} side={THREE.DoubleSide} />
            </mesh>
            {[-1, 1].map((s) => (
                <mesh key={s} position={[s * 0.44, -0.02, 0]} scale={[0.45, 0.9, 0.7]}>
                    <sphereGeometry args={[0.12, 16, 16]} />
                    <meshStandardMaterial color={skin} roughness={0.65} />
                </mesh>
            ))}
            <group ref={eyes} position={[0, 0.03, 0]}>
                {[-1, 1].map((s) => (
                    <group key={s} position={[s * 0.16, 0, 0.4]}>
                        <mesh>
                            <sphereGeometry args={[0.08, 16, 16]} />
                            <meshStandardMaterial color="#ffffff" roughness={0.25} />
                        </mesh>
                        <mesh position={[0, 0, 0.052]}>
                            <sphereGeometry args={[0.04, 16, 16]} />
                            <meshStandardMaterial color={eye} roughness={0.2} />
                        </mesh>
                    </group>
                ))}
            </group>
            <mesh position={[0, -0.06, 0.45]}>
                <sphereGeometry args={[0.04, 12, 12]} />
                <meshStandardMaterial color={skin} roughness={0.7} />
            </mesh>
            <mesh position={[0, -0.15, 0.41]} rotation={[0, 0, Math.PI]}>
                <torusGeometry args={[0.12, 0.016, 8, 24, Math.PI]} />
                <meshStandardMaterial color="#7c4a3a" roughness={0.6} />
            </mesh>
            {[-1, 1].map((s) => (
                <mesh key={s} position={[s * 0.28, -0.12, 0.34]} scale={[1, 0.6, 0.4]}>
                    <sphereGeometry args={[0.055, 12, 12]} />
                    <meshStandardMaterial color="#f2998f" roughness={1} />
                </mesh>
            ))}
        </group>
    );
};

const SeatedAvatar: React.FC<{ config: AvatarConfig; typing: boolean }> = ({ config, typing }) => {
    const c = resolveAvatar(config); // ← fill defaults; `c` is fully ResolvedAvatarConfig
    const root = useRef<THREE.Group>(null!);
    const torso = useRef<THREE.Group>(null!);
    const hands = useRef<Array<THREE.Mesh | null>>([]);

    useFrame((state) => {
        const t = state.clock.elapsedTime;
        hands.current.forEach((h, i) => {
            if (h) h.position.y = HAND_Y + (typing
                ? Math.abs(Math.sin(t * 12 + i * 2.4)) * 0.04
                : Math.sin(t * 1.4 + i * Math.PI) * 0.008);
        });
        if (torso.current) torso.current.scale.y = 1 + Math.sin(t * 1.8) * 0.012;
        if (root.current) root.current.rotation.y = Math.sin(t * 0.6) * 0.03;
    });

    return (
        <group ref={root}>
            <mesh position={[0, 0.58, 0]} scale={[1, 0.75, 1]}>
                <sphereGeometry args={[0.22, 16, 16]} />
                <meshStandardMaterial color={c.skinColor} roughness={0.85} />
            </mesh>
            <group ref={torso} position={[0, 0.94, 0.02]} rotation={[0.09, 0, 0]}>
                <mesh>
                    <capsuleGeometry args={[0.25, 0.4, 8, 20]} />
                    <meshStandardMaterial color={c.shirtColor} roughness={0.78} />
                </mesh>
            </group>
            {[-1, 1].map((s, i) => (
                <group key={s} position={[s * 0.26, 1.14, 0.04]} rotation={[-0.55, 0, -0.14 * s]}>
                    <mesh position={[0, -0.14, 0]}>
                        <capsuleGeometry args={[0.075, 0.2, 4, 12]} />
                        <meshStandardMaterial color={c.shirtColor} roughness={0.78} />
                    </mesh>
                    <group position={[0, -0.28, 0]} rotation={[-1.05, 0, 0]}>
                        <mesh position={[0, -0.13, 0]}>
                            <capsuleGeometry args={[0.065, 0.18, 4, 12]} />
                            <meshStandardMaterial color={c.shirtColor} roughness={0.78} />
                        </mesh>
                        <mesh ref={(el) => { hands.current[i] = el; }} position={[0, HAND_Y, 0.01]}>
                            <sphereGeometry args={[0.085, 14, 14]} />
                            <meshStandardMaterial color={c.skinColor} roughness={0.65} />
                        </mesh>
                    </group>
                </group>
            ))}
            {[-1, 1].map((s) => (
                <group key={s} position={[s * 0.13, 0.54, 0.02]} rotation={[-1.35, 0, 0]}>
                    <mesh position={[0, -0.18, 0]}>
                        <capsuleGeometry args={[0.105, 0.28, 4, 12]} />
                        <meshStandardMaterial color={c.pantsColor} roughness={0.85} />
                    </mesh>
                    <group position={[0, -0.36, 0]} rotation={[1.45, 0, 0]}>
                        <mesh position={[0, -0.16, 0]}>
                            <capsuleGeometry args={[0.085, 0.26, 4, 12]} />
                            <meshStandardMaterial color={c.pantsColor} roughness={0.85} />
                        </mesh>
                        <mesh position={[0, -0.34, 0.04]} scale={[1, 0.55, 1.45]}>
                            <sphereGeometry args={[0.1, 14, 14]} />
                            <meshStandardMaterial color={c.shoeColor} roughness={0.5} />
                        </mesh>
                    </group>
                </group>
            ))}
            <SeatedHead skin={c.skinColor} hair={c.hairColor} eye={c.eyeColor} follow={c.followMouse} />
        </group>
    );
};

/* --------------------------- Clickable seat ------------------------------- */

interface SeatSpotProps {
    seat: TableSeat;
    avatar?: AvatarConfig;
    onStationClick?: (id: StationId) => void;
}

const SeatSpot: React.FC<SeatSpotProps> = ({ seat, avatar, onStationClick }) => {
    const [hovered, setHovered] = useState(false);
    return (
        <group position={seat.position} rotation={[0, seat.rotationY, 0]}>
            <mesh position={[0, 0.004, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <ringGeometry args={[0.33, 0.42, 32]} />
                <meshBasicMaterial color="#6366f1" transparent opacity={hovered ? 0.6 : 0.15} />
            </mesh>
            <Stool />
            {avatar && (
                <Appear>
                    <SeatedAvatar config={avatar} typing={false} />
                </Appear>
            )}
            <mesh
                position={[0, 0.05, 0]}
                onClick={(e: ThreeEvent<MouseEvent>) => { e.stopPropagation(); onStationClick?.(seat.id); }}
                onPointerOver={(e: ThreeEvent<PointerEvent>) => { e.stopPropagation(); setHovered(true); document.body.style.cursor = 'pointer'; }}
                onPointerOut={() => { setHovered(false); document.body.style.cursor = 'auto'; }}
            >
                <cylinderGeometry args={[0.45, 0.45, 0.12, 12]} />
                <meshBasicMaterial transparent opacity={0} depthWrite={false} />
            </mesh>
        </group>
    );
};

/* -------------------------------- Station --------------------------------- */

interface StationProps {
    def: StationDef;
    assignments: AvatarAssignments;
    screensOn: boolean;
    lampOn: boolean;
    onLampToggle: (next: boolean) => void;
    onStationClick?: (id: StationId) => void;
}

const Station: React.FC<StationProps> = ({ def, assignments, screensOn, lampOn, onLampToggle, onStationClick }) => {
    switch (def.kind) {
        case 'table':
            return (
                <group position={def.position}>
                    <RoundTable />
                    {def.seats.map((seat) => (
                        <SeatSpot key={seat.id} seat={seat} avatar={assignments[seat.id]} onStationClick={onStationClick} />
                    ))}
                </group>
            );

        case 'desk': {
            const avatar = assignments[def.id];
            const isTyping = screensOn && (avatar?.typing ?? true);
            return (
                <group
                    position={def.position}
                    rotation={[0, def.rotationY, 0]}
                    onClick={(e: ThreeEvent<MouseEvent>) => { e.stopPropagation(); onStationClick?.(def.id); }}
                >
                    <mesh position={[0, 0.004, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                        <ringGeometry args={[def.hoverRadius - 0.07, def.hoverRadius, 48]} />
                        <meshBasicMaterial color="#6366f1" transparent opacity={0.14} />
                    </mesh>
                    <Desk />
                    <Laptop position={[0.02, DESK_TOP, 0.14]} rotationY={0.05} on={screensOn} />
                    <DeskLamp position={[-0.68, DESK_TOP, -0.26]} rotationY={-0.45} on={lampOn} onToggle={onLampToggle} />
                    <BookStack position={[0.68, DESK_TOP, -0.24]} />
                    <DeskPlant position={[-0.35, DESK_TOP, 0.18]} />
                    <OfficeChair position={def.seat.position} />
                    {avatar && (
                        <Appear>
                            <group position={def.seat.position} rotation={[0, def.seat.rotationY, 0]}>
                                <SeatedAvatar config={avatar} typing={isTyping} />
                            </group>
                        </Appear>
                    )}
                </group>
            );
        }

        default:
            return assertNever(def, 'StationDef.kind'); // exhaustive check
    }
};

/* ------------------------------- Camera ----------------------------------- */

/** Minimal structural type for the OrbitControls instance drei exposes. */
interface OrbitControlsLike {
    target: THREE.Vector3;
    minDistance: number;
    maxDistance: number;
    update: () => void;
}

interface CameraRigProps {
    center: Vec2;
    radius: number;
}

const CameraRig: React.FC<CameraRigProps> = ({ center, radius }) => {
    const get = useThree((s) => s.get);

    useEffect(() => {
        const { camera, controls } = get() as unknown as {
            camera: THREE.PerspectiveCamera;
            controls: OrbitControlsLike | null;
        };

        camera.position.set(
            center[0] + radius * 0.55,
            radius * 0.9 + 1.6,
            center[1] + radius * 1.55 + 2.0
        );

        if (controls) {
            controls.target.set(center[0], 0.9, center[1]);
            controls.minDistance = 2.5;
            controls.maxDistance = radius * 3 + 8;
            controls.update();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [center[0], center[1], radius, get]);

    return null;
};

/* -------------------------------- Scene ----------------------------------- */

interface OfficeSceneProps {
    stations: readonly StationDef[];
    assignments: AvatarAssignments;
    screensOn: boolean;
    controlledLampOn: boolean | undefined;
    defaultLampsOn: boolean;
    onLampToggle?: (id: StationId, on: boolean) => void;
    onStationClick?: (id: StationId) => void;
}

const OfficeScene: React.FC<OfficeSceneProps> = ({
    stations, assignments, screensOn, controlledLampOn, defaultLampsOn, onLampToggle, onStationClick,
}) => {
    const [lampStates, setLampStates] = useState<Partial<Record<StationId, boolean>>>({});
    const getLampOn = (id: StationId): boolean => controlledLampOn ?? lampStates[id] ?? defaultLampsOn;
    const handleLampToggle = (id: StationId) => (next: boolean) => {
        setLampStates((prev) => ({ ...prev, [id]: next }));
        onLampToggle?.(id, next);
    };

    const bounds = useMemo(() => {
        let minX = 0, maxX = 0, minZ = 0, maxZ = 0;
        for (const s of stations) {
            const [x, , z] = s.position;
            const r = s.hoverRadius;
            minX = Math.min(minX, x - r); maxX = Math.max(maxX, x + r);
            minZ = Math.min(minZ, z - r); maxZ = Math.max(maxZ, z + r);
        }
        const center: Vec2 = [(minX + maxX) / 2, (minZ + maxZ) / 2];
        return { center, radius: Math.max(maxX - minX, maxZ - minZ) / 2 + 1 };
    }, [stations]);

    return (
        <>
            <ambientLight intensity={0.85} />
            <directionalLight position={[4, 7, 5]} intensity={1.5} />
            <directionalLight position={[-5, 4, -6]} intensity={0.5} color="#cdd9ff" />

            <mesh rotation={[-Math.PI / 2, 0, 0]}>
                <circleGeometry args={[Math.max(10, bounds.radius * 2.4), 64]} />
                <meshStandardMaterial color="#e6eaf1" roughness={1} />
            </mesh>

            {stations.map((def) => (
                <Station
                    key={def.id}
                    def={def}
                    assignments={assignments}
                    screensOn={screensOn}
                    lampOn={getLampOn(def.kind === 'desk' ? def.id : 'table-0')}
                    onLampToggle={handleLampToggle(def.kind === 'desk' ? def.id : 'table-0')}
                    onStationClick={onStationClick}
                />
            ))}

            <ContactShadows
                position={[0, 0.001, 0]}
                opacity={0.35}
                scale={Math.max(18, bounds.radius * 4)}
                blur={2.4}
                far={3}
                color="#1e293b"
            />
            <OrbitControls makeDefault enablePan={false} maxPolarAngle={Math.PI * 0.49} />
            <CameraRig center={bounds.center} radius={bounds.radius} />
        </>
    );
};

/* ═══════════════════════════ PUBLIC COMPONENT ═════════════════════════════ */

export interface Office3DProps {
    /**
     * Office layout. Fully typed via `OfficeLayout` — every field documented,
     * all values clamped at runtime. Memoize if constructed inline in a hot path.
     * @example { desks: 6, desksPerRow: 3, table: true }
     */
    layout?: OfficeLayout;
    /**
     * Station → avatar map. Keys are compile-checked `StationId`s
     * (`desk-0`, `table-2`, …). Overrides `avatarAt`/`avatar`.
     */
    avatars?: AvatarAssignments;
    /** Convenience: single avatar at one station (ignored if `avatars` given). */
    avatarAt?: StationId | null;
    /** Appearance of the `avatarAt` avatar. */
    avatar?: AvatarConfig;
    /** Auto-fill the first N empty stations with varied procedural avatars. @min 0 */
    autoPopulate?: number;
    /** Laptop screens on/off. @default true */
    screensOn?: boolean;
    /** Controlled lamp state for all desks (omit = click lamps to toggle). */
    lampOn?: boolean;
    /** Initial lamp state when uncontrolled. @default true */
    defaultLampsOn?: boolean;
    /** Fired when a lamp toggles. */
    onLampToggle?: (id: StationId, on: boolean) => void;
    /** Fired with the `StationId` when a desk or stool is clicked. */
    onStationClick?: (id: StationId) => void;
    /**
     * Breakpoint (px) below which the component treats the viewport as
     * "mobile" for the scroll/overflow behavior described on `className`/`style`.
     * @default 768
     */
    mobileBreakpoint?: number;
    className?: string;
    style?: React.CSSProperties;
}

const SKIN: readonly HexColor[] = ['#ffcf9f', '#f0b58a', '#c68863', '#8d5a3b', '#ffd9b3'];
const HAIR: readonly HexColor[] = ['#2f2118', '#0f0d0b', '#5b3a1e', '#8b5e3c', '#4a4a4a', '#b55219'];
const SHIRTS: readonly HexColor[] = ['#6c5ce7', '#0ea5a4', '#e15b64', '#f59e0b', '#10b981', '#3b82f6', '#ec4899'];

/**
 * Tracks whether the viewport is at/below `breakpoint`. Used only to decide
 * the container's overflow/touch-scroll behavior — never affects 3D layout.
 */
function useIsMobileViewport(breakpoint: number): boolean {
    const [isMobile, setIsMobile] = useState<boolean>(() =>
        typeof window !== 'undefined' ? window.innerWidth <= breakpoint : false
    );
    useEffect(() => {
        if (typeof window === 'undefined') return;
        const mq = window.matchMedia(`(max-width: ${breakpoint}px)`);
        const onChange = () => setIsMobile(mq.matches);
        onChange();
        mq.addEventListener('change', onChange);
        return () => mq.removeEventListener('change', onChange);
    }, [breakpoint]);
    return isMobile;
}

export const Office3D: React.FC<Office3DProps> = ({
    layout,
    avatars,
    avatarAt,
    avatar,
    autoPopulate,
    screensOn = true,
    lampOn,
    defaultLampsOn = true,
    onLampToggle,
    onStationClick,
    mobileBreakpoint = 768,
    className,
    style,
}) => {
    const stations = useMemo<StationDef[]>(() => resolveStations(layout), [layout]);
    const isMobile = useIsMobileViewport(mobileBreakpoint);

    const assignments = useMemo<AvatarAssignments>(() => {
        const result: AvatarAssignments = {};

        if (avatars) {
            if (!isAvatarAssignments(avatars)) { // runtime safety net (types can lie at runtime)
                console.warn('[Office3D] `avatars` contains invalid values — ignoring.');
            } else {
                Object.assign(result, avatars);
            }
        } else if (avatarAt) {
            result[avatarAt] = avatar ?? {};
        }

        const fill = Math.max(0, Math.floor(autoPopulate ?? 0));
        if (fill > 0) {
            let filled = Object.keys(result).length;
            for (const id of stationIds(stations)) {
                if (filled >= fill) break;
                if (result[id]) continue;
                result[id] = {
                    skinColor: SKIN[filled % SKIN.length],
                    hairColor: HAIR[filled % HAIR.length],
                    shirtColor: SHIRTS[filled % SHIRTS.length],
                };
                filled++;
            }
        }
        return result;
    }, [avatars, avatarAt, avatar, autoPopulate, stations]);

    return (
        <div
            className={className}
            style={{
                width: '100%',
                height: '100%',
                // Fill the parent exactly — no forced minimum, so the
                // component never grows past (or scrolls within) whatever
                // box it's given. Desktop/tablet: clip anything that would
                // otherwise cause a scrollbar. Mobile: allow the container
                // itself to scroll if its content is taller than the parent,
                // since touch users often expect to be able to scroll past it.
                overflow: isMobile ? 'auto' : 'hidden',
                position: 'relative',
                ...style,
            }}
        >
            <Canvas
                camera={{ position: [2, 4, 9], fov: 38, far: 200 }}
                dpr={[1, 2]}
                gl={{ antialias: true, alpha: true }}
                // `display:'block'` matters: a <canvas> is inline by default,
                // which leaves a few px of baseline gap under it — that gap
                // is what usually causes a container to overflow its parent
                // by just enough to trigger an unwanted scrollbar.
                style={{
                    display: 'block',
                    width: '100%',
                    height: '100%',
                    // On mobile, don't let the canvas swallow one-finger
                    // vertical drags meant for page scrolling; two-finger /
                    // pinch gestures still reach OrbitControls.
                    touchAction: isMobile ? 'pan-y' : 'none',
                }}
            >
                <color attach="background" args={['#edf1f7']} />
                <OfficeScene
                    stations={stations}
                    assignments={assignments}
                    screensOn={screensOn}
                    controlledLampOn={lampOn}
                    defaultLampsOn={defaultLampsOn}
                    onLampToggle={onLampToggle}
                    onStationClick={onStationClick}
                />
            </Canvas>
        </div>
    );
};

export default Office3D;
